language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
    - yarn
    - yarn test || travis_terminate 1;
    - yarn deploy:dev --conceal || travis_terminate 1;
    - yarn sls:remove || travis_terminate 1;